{{- $tracingUrl := include "change-merger.tracingUrl" . -}}
{{- $metricsUrl := include "change-merger.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configmap" (include "change-merger.fullname" .) }}
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  npm_config_cache: /tmp/
  APP_EXTERNAL_ID_TAG: {{ .Values.env.app.externalIdTag  | quote }}
  APP_REMOTE_API_BASE_URL: {{ .Values.env.app.remote.api.baseUrl | quote }}
  APP_REMOTE_API_TIMEOUT_MS: {{ .Values.env.app.remote.api.timeoutMs | quote }}
  APP_REMOTE_REPLICATION_BASE_URL: {{ .Values.env.app.remote.replication.baseUrl | quote }}
  APP_REMOTE_REPLICATION_TIMEOUT_MS: {{ .Values.env.app.remote.replication.timeoutMs | quote }}
{{- end }}
