global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
initialDelaySeconds: 60
environment: development
replicaCount: 1

cloudProvider:
  flavor: openshift
  dockerRegistryUrl: 'my-registry.io'

image:
  repository: change-merger
  tag: 'latest'

env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  requestPayloadLimit: 5mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics

resources:
  enabled: false
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

route:
  enabled: true
  path: /
