global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
initialDelaySeconds: 60
environment: development
replicaCount: 1

annotations: {}
podAnnotations: {}

cloudProvider:
  flavor: openshift
  dockerRegistryUrl: 'my-registry.io'

image:
  repository: change-merger
  # tag: 'latest'
  pullPolicy: Always

env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  requestPayloadLimit: 5mb
  responseCompressionEnabled: true
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
    ratio: 1
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics

resources:
  enabled: true
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

route:
  enabled: true
  tls:
    termination: edge
  path: /
